GET http://localhost:3001/api/notes/

###
GET http://localhost:3001/api/notes/213

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "sample",
    "important": true
}

###
DELETE http://localhost:3001/api/notes/66be3369bc10a81271ca2fe6